package com.monster.cargo.model;

public class SuperCargoInfoDo {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column super_cargo_info.CARGO_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   private String cargoId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column super_cargo_info.CARGO_TYPE_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   private String cargoTypeId;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column super_cargo_info.CARGO_ID
    *
    * @return the value of super_cargo_info.CARGO_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   public String getCargoId() {
       return cargoId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column super_cargo_info.CARGO_ID
    *
    * @param cargoId the value for super_cargo_info.CARGO_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   public void setCargoId(String cargoId) {
       this.cargoId = cargoId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column super_cargo_info.CARGO_TYPE_ID
    *
    * @return the value of super_cargo_info.CARGO_TYPE_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   public String getCargoTypeId() {
       return cargoTypeId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column super_cargo_info.CARGO_TYPE_ID
    *
    * @param cargoTypeId the value for super_cargo_info.CARGO_TYPE_ID
    *
    * @mbg.generated Tue Nov 05 10:41:59 CST 2019
    */
   public void setCargoTypeId(String cargoTypeId) {
       this.cargoTypeId = cargoTypeId;
   }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_cargo_info.CUST_ID
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    private String custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_cargo_info.CARGO_DATE
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    private String cargoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_cargo_info.CARGO_TIME
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    private String cargoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column super_cargo_info.STAT
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    private String stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_cargo_info.CUST_ID
     *
     * @return the value of super_cargo_info.CUST_ID
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_cargo_info.CUST_ID
     *
     * @param custId the value for super_cargo_info.CUST_ID
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_cargo_info.CARGO_DATE
     *
     * @return the value of super_cargo_info.CARGO_DATE
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public String getCargoDate() {
        return cargoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_cargo_info.CARGO_DATE
     *
     * @param cargoDate the value for super_cargo_info.CARGO_DATE
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public void setCargoDate(String cargoDate) {
        this.cargoDate = cargoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_cargo_info.CARGO_TIME
     *
     * @return the value of super_cargo_info.CARGO_TIME
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public String getCargoTime() {
        return cargoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_cargo_info.CARGO_TIME
     *
     * @param cargoTime the value for super_cargo_info.CARGO_TIME
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public void setCargoTime(String cargoTime) {
        this.cargoTime = cargoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column super_cargo_info.STAT
     *
     * @return the value of super_cargo_info.STAT
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column super_cargo_info.STAT
     *
     * @param stat the value for super_cargo_info.STAT
     *
     * @mbg.generated Tue Nov 05 10:41:59 CST 2019
     */
    public void setStat(String stat) {
        this.stat = stat;
    }
}